# Generated by Django 5.1.4 on 2024-12-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Dr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.CharField(max_length=255, null=True)),
                ('booking_date', models.CharField(max_length=255, null=True)),
                ('details', models.TextField(max_length=255, null=True)),
                ('p_status', models.CharField(max_length=255, null=True)),
                ('f_status', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DutyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_start', models.CharField(max_length=255, null=True)),
                ('evening_start', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
