# Generated by Django 5.1.4 on 2025-01-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_dr',
            old_name='p_status',
            new_name='c_status',
        ),
    ]
