# Generated by Django 5.1.4 on 2024-12-21 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
        ('user_app', '0002_register_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.disease'),
        ),
    ]
