# Generated by Django 5.1.4 on 2024-12-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
        ('user_app', '0003_register_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='disease',
        ),
        migrations.AddField(
            model_name='register',
            name='disease',
            field=models.ManyToManyField(null=True, to='disease.disease'),
        ),
    ]
