# Generated by Django 5.1.7 on 2025-03-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_register_reject_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='disease',
        ),
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
